# Generated by Django 2.2.16 on 2023-03-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='content',
        ),
        migrations.RemoveField(
            model_name='car',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='car',
            name='time_update',
        ),
        migrations.RemoveField(
            model_name='car',
            name='title',
        ),
        migrations.AddField(
            model_name='car',
            name='body',
            field=models.CharField(choices=[('Hatchback', 'Хэтчбек'), ('Sedan', 'Седан'), ('SUV', 'Внедорожник'), ('CUV', 'Кроссовер'), ('Van', 'Фургон'), ('Coupe ', 'Купе'), ('Estate', 'Универсал'), ('Truck', 'Грузовик'), ('Pickup', 'Пикап'), ('LiftBack', 'Лифтбэк')], default='Кузов не выбран', max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='mark',
            field=models.CharField(choices=[('Audi', 'Ауди'), ('BMW', 'БМВ'), ('Cirtoen', 'Ситроен'), ('Dodge', 'Додж'), ('Fiat', 'Фиат'), ('Ford', 'Форд'), ('Jelly', 'Джелли'), ('Jaguar', 'Ягуар'), ('Honda', 'Хонда'), ('Hyundai', 'Хёндэ'), ('KIA', 'Киа'), ('Lexus', 'Лексус'), ('Land Rover', 'Ленд Ровер'), ('Mersedes', 'Мерседес'), ('Mini', 'Мини'), ('Mazda', 'Мазда'), ('Mitsubishi', 'Митсубиси'), ('Nissan', 'Ниссан'), ('Ravon', 'Равон'), ('Renault', 'Рено'), ('Smart', 'Смарт'), ('Skoda', 'Шкода'), ('Toyota', 'Тойота'), ('Volkswagen', 'Фольксваген'), ('Volvo', 'Вольво'), ('Lada', 'Лада'), ('VAZ', 'ВАЗ'), ('UAZ', 'УАЗ')], default='Марка не выбрана', max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.CharField(default='Модель  не выбрана', max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.IntegerField(default=2023),
        ),
    ]
