# Generated by Django 2.2.16 on 2023-03-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20230317_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='complect',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
