# Generated by Django 2.2.16 on 2023-03-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_car_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='mark',
            field=models.CharField(choices=[('Audi', 'Audi'), ('BMW', 'BMW'), ('Cirtoen', 'Cirtoen'), ('Dodge', 'Dodge'), ('Fiat', 'Fiat'), ('Ford', 'Ford'), ('Jelly', 'Jelly'), ('Jaguar', 'Jaguar'), ('Honda', 'Honda'), ('Hyundai', 'Hyundai'), ('KIA', 'KIA'), ('Lexus', 'Lexus'), ('Land Rover', 'Land Rover'), ('Mersedes', 'Mersedes'), ('Mini', 'Mini'), ('Mazda', 'Mazda'), ('Mitsubishi', 'Mitsubishi'), ('Nissan', 'Nissan'), ('Ravon', 'Ravon'), ('Renault', 'Renault'), ('Smart', 'Smart'), ('Skoda', 'Skoda'), ('Toyota', 'Toyota'), ('Volkswagen', 'Volkswagen'), ('Volvo', 'Volvo'), ('Lada', 'Лада'), ('VAZ', 'ВАЗ'), ('UAZ', 'УАЗ')], default='Марка не выбрана', max_length=50),
        ),
    ]
