# Generated by Django 2.2.16 on 2023-03-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_auto_20230317_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(default='Модель не выбрана', max_length=100),
        ),
    ]
