events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile on;
    keepalive_timeout 65;

    resolver 127.0.0.11 valid=30s ipv6=off;

    server {
        listen 80;
        server_name drivelog.live www.drivelog.live _;

        root /usr/share/nginx/html;
        index index.html;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        include /etc/nginx/snippets/app-locations.conf;
    }
}
