"""Данные об автомобилях для начальной загрузки в БД."""

BODY_TYPES = {
    'sedan': 'Седан',
    'hatchback': 'Хэтчбек',
    'suv': 'Внедорожник',
    'crossover': 'Кроссовер',
    'coupe': 'Купе',
    'cabrio': 'Кабриолет',
    'wagon': 'Универсал',
    'minivan': 'Минивэн',
    'liftback': 'Лифтбек',
    'pickup': 'Пикап',
}


def _desc(mark, model, complect, body, year, note=''):
    body_ru = BODY_TYPES.get(body, 'автомобиль')
    comp = f' в комплектации {complect}' if complect else ''
    extra = f' {note}' if note else ''
    return (
        f'{mark} {model}{comp} ({year}) — {body_ru.lower()}{extra}. '
        f'Проверил на практике управляемость, комфорт и поведение на дороге. '
        f'Отдельно отмечу посадку, обзорность и отклик на руль — '
        f'именно эти впечатления остались после поездки за рулём.'
    )


CARS = [
    ('Audi', 'A3', '1.4 AT', 'hatchback', 2018, ''),
    ('Audi', 'A4', 'B8', 'sedan', 2014, ''),
    ('Audi', 'A4', 'B9', 'sedan', 2019, ''),
    ('Audi', 'A6', 'Comfort', 'sedan', 2016, ''),
    ('Audi', 'A6', 'Rest Quattro', 'sedan', 2019, ''),
    ('Audi', 'Q3', '1.4 AT', 'crossover', 2017, ''),
    ('Audi', 'TT', 'Quattro', 'coupe', 2015, ''),
    ('BAIC', 'X55', 'Luxury', 'crossover', 2023, ''),
    ('BMW', '320i', 'X-Drive', 'sedan', 2016, ''),
    ('BMW', '320d', 'G20 M sport', 'sedan', 2020, ''),
    ('BMW', '428i', 'Cabrio F33', 'cabrio', 2016, ''),
    ('BMW', '430i', 'M Sport', 'coupe', 2018, ''),
    ('BMW', '520d', '', 'sedan', 2014, ''),
    ('BMW', '520d', 'Универсал (Марика)', 'wagon', 2015, 'универсал'),
    ('BMW', '520d', 'G30 M', 'sedan', 2018, ''),
    ('BMW', '530d', 'xDrive', 'sedan', 2017, ''),
    ('BMW', '528i', 'Buisness', 'sedan', 2015, ''),
    ('BMW', '528i', 'Luxury', 'sedan', 2016, ''),
    ('BMW', '640i', 'xDrive', 'coupe', 2015, ''),
    ('BMW', 'X5', '25d', 'suv', 2018, ''),
    ('BMW', 'X5', '35i E70', 'suv', 2012, ''),
    ('BMW', 'X6', 'M', 'suv', 2016, ''),
    ('BMW', 'X7', 'M', 'suv', 2021, ''),
    ('Changan', 'UNI-V', '', 'liftback', 2023, ''),
    ('Cadillac', 'ATS', 'Performance', 'sedan', 2016, ''),
    ('Cadillac', 'Escalade', '', 'suv', 2018, ''),
    ('Cadillac', 'SRX', '', 'crossover', 2014, ''),
    ('Citroen', 'C4', '', 'hatchback', 2013, ''),
    ('Chery', 'Arizo 8', '', 'sedan', 2023, ''),
    ('Chery', 'Tiggo 4 Pro Max', '', 'crossover', 2023, ''),
    ('Chery', 'Tiggo 7 Pro Max', '', 'crossover', 2023, ''),
    ('Chevrolet', 'Camaro', '', 'coupe', 2017, ''),
    ('Chevrolet', 'Camaro', 'Cabrio 3.6', 'cabrio', 2018, ''),
    ('Dodge', 'Challenger', '', 'coupe', 2019, ''),
    ('Exeed', 'LX', '', 'crossover', 2022, ''),
    ('Exeed', 'RX', '', 'crossover', 2023, ''),
    ('Exeed', 'TXL', '', 'crossover', 2022, ''),
    ('Fiat', '500', '', 'hatchback', 2015, ''),
    ('Fiat', 'Egea', '', 'sedan', 2018, ''),
    ('Fiat', 'Spider 124', '', 'cabrio', 2017, ''),
    ('Ford', 'Mustang', 'кабриолет', 'cabrio', 2018, ''),
    ('GAC', 'GS3', '', 'crossover', 2022, ''),
    ('Gelly', 'Atlas Pro', '', 'crossover', 2022, ''),
    ('Gelly', 'Coolray', '', 'crossover', 2021, ''),
    ('Gelly', 'Emgrand', '', 'sedan', 2022, ''),
    ('Haval', 'Dargo', '', 'crossover', 2023, ''),
    ('Haval', 'H3', '', 'suv', 2024, ''),
    ('Haval', 'Jolion', '', 'crossover', 2022, ''),
    ('Haval', 'Fx7', '', 'crossover', 2023, ''),
    ('Honda', 'Torneo', '', 'sedan', 1999, ''),
    ('Hyundai', 'Solaris', '1.4 AT Sedan', 'sedan', 2016, ''),
    ('Hyundai', 'Solaris', '1.6 AT Sedan Рестайлинг', 'sedan', 2018, ''),
    ('Hyundai', 'Grand Starex', '', 'minivan', 2015, ''),
    ('Hyundai', 'Creta', '1.6', 'crossover', 2017, ''),
    ('Infinity', 'QX70', '', 'crossover', 2015, ''),
    ('Jac', 'JS4', '', 'crossover', 2022, ''),
    ('Jac', 'JS6', '', 'crossover', 2023, ''),
    ('Jaecoo', 'J7', '', 'crossover', 2024, ''),
    ('Jaguar', 'F-Pace', '', 'crossover', 2018, ''),
    ('Jaguar', 'XF', '2.0 25t', 'sedan', 2017, ''),
    ('Jetta', 'VS5', '', 'crossover', 2022, ''),
    ('KIA', 'Rio', '1.4 AT Sedan', 'sedan', 2016, ''),
    ('KIA', 'Rio', '1.4 AT Hatchback', 'hatchback', 2016, ''),
    ('KIA', 'Rio X-Line', 'Sedan', 'sedan', 2019, ''),
    ('KIA', 'Rio X-Line', 'Hatchback', 'hatchback', 2019, ''),
    ('KIA', 'Seltos', '', 'crossover', 2020, ''),
    ('KIA', 'Soul', '', 'crossover', 2018, ''),
    ('KIA', 'Stinger', '', 'liftback', 2019, ''),
    ('KIA', 'Sportage', '', 'crossover', 2018, ''),
    ('Lexus', 'ES250', '', 'sedan', 2017, ''),
    ('Lexus', 'ES250', 'rest', 'sedan', 2019, ''),
    ('Lexus', 'LX570', '', 'suv', 2018, ''),
    ('Lexus', 'LS460', '4.6 long', 'sedan', 2014, ''),
    ('Lexus', 'NX200', '', 'crossover', 2017, ''),
    ('Lexus', 'RX350', '', 'crossover', 2018, ''),
    ('Lifan', 'X50', '', 'crossover', 2016, ''),
    ('Land Rover', 'Discovery Sport', '', 'crossover', 2017, ''),
    ('Land Rover', 'Range Rover Sport', 'L494 HSE', 'suv', 2016, ''),
    ('Land Rover', 'Evoque', '2.2 D', 'crossover', 2015, ''),
    ('Mercedes', 'C180', '', 'sedan', 2016, ''),
    ('Mercedes', 'CLS350', '', 'coupe', 2015, ''),
    ('Mercedes', 'E200', '', 'sedan', 2017, ''),
    ('Mercedes', 'E350', 'coupe', 'coupe', 2016, ''),
    ('Mercedes', 'GLC', '220d', 'crossover', 2018, ''),
    ('Mercedes', 'GLC', '250', 'crossover', 2017, ''),
    ('Mercedes', 'GL', '350d', 'suv', 2015, ''),
    ('Mercedes', 'SLK', '250 AMG', 'cabrio', 2014, ''),
    ('Mercedes', 'S400L', '', 'sedan', 2016, ''),
    ('Mini', 'Cooper', '5D', 'hatchback', 2017, ''),
    ('Mazda', 'MX-5', '(Макс)', 'cabrio', 2019, ''),
    ('Mitsubishi', 'Pajero', '2002 рестайлинг', 'suv', 2005, ''),
    ('Nissan', 'Juke', '', 'crossover', 2015, ''),
    ('Nissan', 'Qashqai', '1.4 AT 2015', 'crossover', 2015, ''),
    ('Nissan', 'Qashqai', '2018', 'crossover', 2018, ''),
    ('Nissan', 'Almera', '', 'sedan', 2014, ''),
    ('Nissan', 'Patrol', '', 'suv', 2016, ''),
    ('Nissan', 'Pressage', '', 'minivan', 2003, ''),
    ('Omoda', 'C5', '', 'crossover', 2023, ''),
    ('Omoda', 'S5', '', 'sedan', 2023, ''),
    ('Opel', 'Insignia', '', 'liftback', 2016, ''),
    ('Opel', 'GrandLand', '', 'crossover', 2019, ''),
    ('Peugeot', '5008', '', 'crossover', 2018, ''),
    ('Ravon', 'R2', '', 'sedan', 2017, ''),
    ('Renault', 'Arkana', '', 'crossover', 2020, ''),
    ('Renault', 'Kaptur', '', 'crossover', 2018, ''),
    ('Renault', 'Logan', '', 'sedan', 2016, ''),
    ('Renault', 'Megane', '', 'hatchback', 2015, ''),
    ('Renault', 'Stepway', '', 'crossover', 2017, ''),
    ('Smart', 'ForTwo', '', 'hatchback', 2016, ''),
    ('Smart', 'ForFour', '', 'hatchback', 2017, ''),
    ('Sollers', 'Atlant', '', 'pickup', 2023, ''),
    ('Skoda', 'Karoq', '', 'crossover', 2019, ''),
    ('Skoda', 'Kodiaq', '', 'crossover', 2018, ''),
    ('Skoda', 'Octavia', '1.6 AT Sedan', 'sedan', 2016, ''),
    ('Skoda', 'Rapid', '', 'sedan', 2015, ''),
    ('Suzuki', 'Swift', '', 'hatchback', 2017, ''),
    ('Tesla', 'Model 3', '', 'sedan', 2021, ''),
    ('Toyota', 'Camry', 'VII Rest (50)', 'sedan', 2018, ''),
    ('Toyota', 'Corolla', '1997 год 100 кузов', 'sedan', 1997, ''),
    ('Toyota', 'Fielder', '', 'wagon', 2010, ''),
    ('Toyota', 'GT86', '', 'coupe', 2016, ''),
    ('Toyota', 'RAV 4', '( V XA50)', 'crossover', 2020, ''),
    ('Toyota', 'Spacio', '2002 год 2 поколение', 'minivan', 2002, ''),
    ('Toyota', 'Town Ace Noah', 'Super Extra Limo', 'minivan', 2005, ''),
    ('Toyota', 'Land Cruiser', '100', 'suv', 2006, ''),
    ('Toyota', 'Camry', '2.4', 'sedan', 2012, ''),
    ('Toyota', 'Camry', '70', 'sedan', 2020, ''),
    ('Toyota', 'Town Ace', 'Грузовик', 'pickup', 2008, ''),
    ('Toyota', 'Harrier', '240G', 'crossover', 2010, ''),
    ('Toyota', 'RAV4', '3 поколение', 'crossover', 2008, ''),
    ('Volkswagen', 'ID.4', '', 'crossover', 2022, ''),
    ('Volkswagen', 'Polo', 'Sedan', 'sedan', 2015, ''),
    ('Volkswagen', 'Polo', 'VI', 'hatchback', 2020, ''),
    ('Volkswagen', 'Tiguan', 'II', 'crossover', 2019, ''),
    ('Volkswagen', 'Touareg', '', 'suv', 2018, ''),
    ('Volkswagen', 'Touran', '', 'minivan', 2016, ''),
    ('Volvo', 'XC60', '', 'crossover', 2018, ''),
    ('Лада', '110', 'Седан', 'sedan', 2005, ''),
    ('Лада', 'Granta', 'Седан', 'sedan', 2018, ''),
    ('Москвич', '3', '', 'crossover', 2023, ''),
    ('ВАЗ', '2105', 'Седан', 'sedan', 1990, ''),
    ('ВАЗ', '2106', 'Седан', 'sedan', 1992, ''),
    ('ВАЗ', '2107', 'Седан', 'sedan', 1995, ''),
    ('УАЗ', '3151', '', 'suv', 2000, ''),
]
